// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CalendarEvent.EF
{
    public partial class EventScheduler
    {
        [Key]
        [Column("eventid")]
        public int Eventid { get; set; }
        [Column("eventdate", TypeName = "date")]
        public DateTime Eventdate { get; set; }
        [Required]
        [Column("userid")]
        [StringLength(10)]
        public string Userid { get; set; }
        [Required]
        [Column("title")]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }
        [Column("start_at")]
        public TimeSpan StartAt { get; set; }
        [Column("end_at")]
        public TimeSpan EndAt { get; set; }
        [Column("created_date", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Required]
        [Column("create_by")]
        [StringLength(10)]
        public string CreateBy { get; set; }
        [Column("updated_date", TypeName = "datetime")]
        public DateTime UpdatedDate { get; set; }
        [Required]
        [Column("updated_by")]
        [StringLength(10)]
        public string UpdatedBy { get; set; }
    }
}